export type Exercise = { name: string; durationSec: number; rest?: number; cue?: string };
export type Workout = {
  key: string;
  name: string;
  category: "Pilates" | "HIIT" | "Yoga" | "Strength" | "Calisthenics";
  level: "Beginner" | "Intermediate" | "Advanced";
  durationMin: number;
  caloriesEstimate: number;
  description: string;
  image: string;
  youtubeUrl: string;
  exercises: Exercise[];
};

export const WORKOUTS: Workout[] = [
  {
    key: "pilates-core",
    name: "Pilates Core Flow",
    category: "Pilates", level: "Beginner", durationMin: 15, caloriesEstimate: 110,
    description: "Slow, controlled core work to build deep abdominal strength.",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=15+minute+pilates+core+workout",
    exercises: [
      { name: "Hundred", durationSec: 60, cue: "Pump arms, exhale strongly" },
      { name: "Single-leg stretch", durationSec: 60, rest: 15 },
      { name: "Roll-up", durationSec: 60, rest: 15 },
      { name: "Toe taps", durationSec: 60, rest: 15 },
      { name: "Plank", durationSec: 45, rest: 30 },
      { name: "Side plank L", durationSec: 30, rest: 15 },
      { name: "Side plank R", durationSec: 30, rest: 15 },
      { name: "Cool-down stretch", durationSec: 90 },
    ],
  },
  {
    key: "pilates-flexibility",
    name: "Pilates Flexibility & Stretch",
    category: "Pilates", level: "Beginner", durationMin: 18, caloriesEstimate: 95,
    description: "Improve flexibility and mobility with gentle pilates stretches.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=pilates+flexibility+stretch+routine",
    exercises: [
      { name: "Spine stretch forward", durationSec: 60 },
      { name: "Saw", durationSec: 60, rest: 15 },
      { name: "Mermaid stretch", durationSec: 45, rest: 15 },
      { name: "Leg circles", durationSec: 60, rest: 15 },
      { name: "Spine twist", durationSec: 60, rest: 15 },
      { name: "Shoulder rolls", durationSec: 45, rest: 15 },
      { name: "Cool-down", durationSec: 90 },
    ],
  },
  {
    key: "pilates-advanced",
    name: "Advanced Pilates Challenge",
    category: "Pilates", level: "Advanced", durationMin: 35, caloriesEstimate: 180,
    description: "Advanced pilates movements for experienced practitioners.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=advanced+pilates+workout+challenge",
    exercises: [
      { name: "Teaser", durationSec: 45, rest: 20 },
      { name: "Boomerang", durationSec: 45, rest: 20 },
      { name: "Corkscrew", durationSec: 45, rest: 20 },
      { name: "Jackknife", durationSec: 45, rest: 20 },
      { name: "Seal", durationSec: 60, rest: 20 },
      { name: "Swan dive", durationSec: 45, rest: 20 },
      { name: "Leg pull front", durationSec: 45, rest: 20 },
    ],
  },
  {
    key: "hiit-burner",
    name: "20-Min HIIT Burner",
    category: "HIIT", level: "Intermediate", durationMin: 20, caloriesEstimate: 240,
    description: "Bodyweight intervals to spike heart rate and burn fat.",
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=20+min+hiit+workout+no+equipment",
    exercises: [
      { name: "Jumping jacks", durationSec: 40, rest: 20 },
      { name: "Squat jumps", durationSec: 40, rest: 20 },
      { name: "Push-ups", durationSec: 40, rest: 20 },
      { name: "Mountain climbers", durationSec: 40, rest: 20 },
      { name: "Burpees", durationSec: 40, rest: 20 },
      { name: "High knees", durationSec: 40, rest: 20 },
      { name: "Plank to shoulder tap", durationSec: 40, rest: 20 },
      { name: "Reverse lunges", durationSec: 40, rest: 20 },
    ],
  },
  {
    key: "hiit-cardio-blast",
    name: "Cardio Blast HIIT",
    category: "HIIT", level: "Advanced", durationMin: 25, caloriesEstimate: 300,
    description: "High-intensity cardio intervals for maximum calorie burn.",
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=cardio+blast+hiit+workout+advanced",
    exercises: [
      { name: "Jump rope", durationSec: 45, rest: 15 },
      { name: "Box jumps", durationSec: 45, rest: 15 },
      { name: "Burpee box jumps", durationSec: 45, rest: 15 },
      { name: "Speed skaters", durationSec: 45, rest: 15 },
      { name: "Tuck jumps", durationSec: 45, rest: 15 },
      { name: "Mountain climbers", durationSec: 45, rest: 15 },
      { name: "Cool-down walk", durationSec: 60 },
    ],
  },
  {
    key: "hiit-tabata",
    name: "Tabata Protocol",
    category: "HIIT", level: "Intermediate", durationMin: 16, caloriesEstimate: 200,
    description: "Classic 20/10 Tabata intervals for efficient training.",
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=tabata+protocol+workout",
    exercises: [
      { name: "Squat thrusts", durationSec: 20, rest: 10 },
      { name: "Push-ups", durationSec: 20, rest: 10 },
      { name: "High knees", durationSec: 20, rest: 10 },
      { name: "Burpees", durationSec: 20, rest: 10 },
      { name: "Jumping lunges", durationSec: 20, rest: 10 },
      { name: "Rest", durationSec: 60 },
    ],
  },
  {
    key: "yoga-morning",
    name: "Morning Yoga Wake-Up",
    category: "Yoga", level: "Beginner", durationMin: 12, caloriesEstimate: 70,
    description: "Gentle stretches and sun salutations to start the day.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=morning+yoga+wake+up+routine",
    exercises: [
      { name: "Child's pose", durationSec: 60 },
      { name: "Cat-cow", durationSec: 60 },
      { name: "Downward dog", durationSec: 60 },
      { name: "Sun salutation A", durationSec: 120 },
      { name: "Warrior II", durationSec: 60 },
      { name: "Triangle pose", durationSec: 60 },
      { name: "Seated twist", durationSec: 60 },
      { name: "Savasana", durationSec: 120 },
    ],
  },
  {
    key: "yoga-vinyasa",
    name: "Vinyasa Flow",
    category: "Yoga", level: "Intermediate", durationMin: 30, caloriesEstimate: 150,
    description: "Dynamic flowing yoga sequence linking breath with movement.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=vinyasa+flow+yoga+30+minutes",
    exercises: [
      { name: "Sun salutation A", durationSec: 120 },
      { name: "Sun salutation B", durationSec: 120 },
      { name: "Warrior flow", durationSec: 120 },
      { name: "Triangle to extended side angle", durationSec: 120 },
      { name: "Downward dog", durationSec: 60 },
      { name: "Chaturanga flow", durationSec: 120 },
      { name: "Savasana", durationSec: 180 },
    ],
  },
  {
    key: "yoga-restorative",
    name: "Restorative Yoga",
    category: "Yoga", level: "Beginner", durationMin: 25, caloriesEstimate: 60,
    description: "Gentle, supported poses for deep relaxation and recovery.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=restorative+yoga+relaxation",
    exercises: [
      { name: "Supported child's pose", durationSec: 120 },
      { name: "Supported forward fold", durationSec: 120 },
      { name: "Reclined butterfly", durationSec: 120 },
      { name: "Legs up the wall", durationSec: 180 },
      { name: "Savasana", durationSec: 180 },
    ],
  },
  {
    key: "strength-full",
    name: "Full-Body Strength",
    category: "Strength", level: "Intermediate", durationMin: 30, caloriesEstimate: 280,
    description: "Compound lifts targeting major muscle groups (dumbbells).",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=full+body+dumbbell+strength+workout",
    exercises: [
      { name: "Goblet squats", durationSec: 60, rest: 30 },
      { name: "Romanian deadlifts", durationSec: 60, rest: 30 },
      { name: "Bench press", durationSec: 60, rest: 30 },
      { name: "Bent-over rows", durationSec: 60, rest: 30 },
      { name: "Overhead press", durationSec: 60, rest: 30 },
      { name: "Walking lunges", durationSec: 60, rest: 30 },
      { name: "Plank", durationSec: 60, rest: 30 },
    ],
  },
  {
    key: "strength-upper",
    name: "Upper Body Strength",
    category: "Strength", level: "Intermediate", durationMin: 28, caloriesEstimate: 240,
    description: "Focused upper body workout targeting chest, back, and arms.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=upper+body+strength+dumbbell+workout",
    exercises: [
      { name: "Dumbbell bench press", durationSec: 60, rest: 30 },
      { name: "Bent-over rows", durationSec: 60, rest: 30 },
      { name: "Dumbbell flyes", durationSec: 60, rest: 30 },
      { name: "Bicep curls", durationSec: 60, rest: 30 },
      { name: "Tricep extensions", durationSec: 60, rest: 30 },
      { name: "Shoulder raises", durationSec: 60, rest: 30 },
      { name: "Cool-down stretch", durationSec: 90 },
    ],
  },
  {
    key: "strength-lower",
    name: "Lower Body Strength",
    category: "Strength", level: "Intermediate", durationMin: 32, caloriesEstimate: 260,
    description: "Build leg strength with squats, lunges, and deadlifts.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=lower+body+strength+workout+dumbbells",
    exercises: [
      { name: "Goblet squats", durationSec: 60, rest: 30 },
      { name: "Bulgarian split squats", durationSec: 60, rest: 30 },
      { name: "Romanian deadlifts", durationSec: 60, rest: 30 },
      { name: "Walking lunges", durationSec: 60, rest: 30 },
      { name: "Calf raises", durationSec: 60, rest: 30 },
      { name: "Glute bridges", durationSec: 60, rest: 30 },
      { name: "Cool-down", durationSec: 90 },
    ],
  },
  {
    key: "calis-push-pull",
    name: "Calisthenics Push & Pull",
    category: "Calisthenics", level: "Advanced", durationMin: 25, caloriesEstimate: 220,
    description: "Bodyweight push and pull skills.",
    image: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=calisthenics+push+pull+workout",
    exercises: [
      { name: "Pull-ups", durationSec: 45, rest: 30 },
      { name: "Dips", durationSec: 45, rest: 30 },
      { name: "Pike push-ups", durationSec: 45, rest: 30 },
      { name: "Inverted rows", durationSec: 45, rest: 30 },
      { name: "Diamond push-ups", durationSec: 45, rest: 30 },
      { name: "Hollow hold", durationSec: 45, rest: 30 },
      { name: "Superman hold", durationSec: 45, rest: 30 },
    ],
  },
  {
    key: "calis-bodyweight",
    name: "Bodyweight Basics",
    category: "Calisthenics", level: "Beginner", durationMin: 20, caloriesEstimate: 150,
    description: "Fundamental bodyweight exercises for beginners.",
    image: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=bodyweight+exercises+beginner+workout",
    exercises: [
      { name: "Push-ups", durationSec: 45, rest: 20 },
      { name: "Squats", durationSec: 45, rest: 20 },
      { name: "Lunges", durationSec: 45, rest: 20 },
      { name: "Plank", durationSec: 45, rest: 20 },
      { name: "Glute bridges", durationSec: 45, rest: 20 },
      { name: "Tricep dips", durationSec: 45, rest: 20 },
      { name: "Cool-down", durationSec: 60 },
    ],
  },
  {
    key: "calis-advanced",
    name: "Advanced Calisthenics",
    category: "Calisthenics", level: "Advanced", durationMin: 35, caloriesEstimate: 280,
    description: "Advanced bodyweight skills and progressions.",
    image: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=advanced+calisthenics+skills+workout",
    exercises: [
      { name: "Muscle-ups", durationSec: 45, rest: 30 },
      { name: "Handstand hold", durationSec: 45, rest: 30 },
      { name: "Planche lean", durationSec: 45, rest: 30 },
      { name: "Front lever", durationSec: 45, rest: 30 },
      { name: "L-sit", durationSec: 45, rest: 30 },
      { name: "Human flag", durationSec: 45, rest: 30 },
      { name: "Cool-down", durationSec: 90 },
    ],
  },
  {
    key: "pilates-mat",
    name: "Pilates Mat Workout",
    category: "Pilates", level: "Intermediate", durationMin: 22, caloriesEstimate: 140,
    description: "Full-body mat pilates focusing on core strength and flexibility.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=pilates+mat+workout+full+body",
    exercises: [
      { name: "Warm-up breathing", durationSec: 60 },
      { name: "Hundred", durationSec: 60, rest: 15 },
      { name: "Roll-up", durationSec: 60, rest: 15 },
      { name: "Leg circles", durationSec: 60, rest: 15 },
      { name: "Rolling like a ball", durationSec: 60, rest: 15 },
      { name: "Single leg stretch", durationSec: 60, rest: 15 },
      { name: "Spine stretch", durationSec: 60, rest: 15 },
      { name: "Cool-down", durationSec: 90 },
    ],
  },
  {
    key: "pilates-reformer",
    name: "Reformer Pilates",
    category: "Pilates", level: "Advanced", durationMin: 40, caloriesEstimate: 200,
    description: "Intense reformer-based pilates for deep muscle engagement.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=reformer+pilates+workout+advanced",
    exercises: [
      { name: "Footwork series", durationSec: 120, rest: 20 },
      { name: "Leg springs", durationSec: 120, rest: 20 },
      { name: "Straps work", durationSec: 120, rest: 20 },
      { name: "Jumping series", durationSec: 90, rest: 20 },
      { name: "Cool-down stretch", durationSec: 120 },
    ],
  },
  {
    key: "hiit-kickboxing",
    name: "Kickboxing HIIT",
    category: "HIIT", level: "Advanced", durationMin: 30, caloriesEstimate: 350,
    description: "High-energy kickboxing intervals for cardio and power.",
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=kickboxing+hiit+workout+30+minutes",
    exercises: [
      { name: "Warm-up jabs", durationSec: 60, rest: 15 },
      { name: "Jab-cross combos", durationSec: 40, rest: 20 },
      { name: "Front kicks", durationSec: 40, rest: 20 },
      { name: "Roundhouse kicks", durationSec: 40, rest: 20 },
      { name: "Knee strikes", durationSec: 40, rest: 20 },
      { name: "Burpee to kick", durationSec: 40, rest: 20 },
      { name: "Cool-down walk", durationSec: 60 },
    ],
  },
  {
    key: "hiit-jump-rope",
    name: "Jump Rope Intervals",
    category: "HIIT", level: "Beginner", durationMin: 15, caloriesEstimate: 180,
    description: "Simple jump rope intervals for quick cardio sessions.",
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=jump+rope+intervals+beginner+workout",
    exercises: [
      { name: "Warm-up", durationSec: 60 },
      { name: "Jump rope", durationSec: 30, rest: 30 },
      { name: "Jump rope", durationSec: 30, rest: 30 },
      { name: "Jump rope", durationSec: 30, rest: 30 },
      { name: "Jump rope", durationSec: 30, rest: 30 },
      { name: "Jump rope", durationSec: 30, rest: 30 },
      { name: "Cool-down", durationSec: 60 },
    ],
  },
  {
    key: "yoga-power",
    name: "Power Yoga",
    category: "Yoga", level: "Advanced", durationMin: 45, caloriesEstimate: 200,
    description: "Dynamic, strength-building yoga flow for experienced practitioners.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=power+yoga+advanced+workout",
    exercises: [
      { name: "Sun salutation A", durationSec: 120 },
      { name: "Sun salutation B", durationSec: 120 },
      { name: "Warrior flow", durationSec: 120 },
      { name: "Chair pose flow", durationSec: 120 },
      { name: "Plank to chaturanga flow", durationSec: 120 },
      { name: "Arm balance practice", durationSec: 120 },
      { name: "Cool-down", durationSec: 180 },
    ],
  },
  {
    key: "yoga-yin",
    name: "Yin Yoga",
    category: "Yoga", level: "Beginner", durationMin: 50, caloriesEstimate: 80,
    description: "Slow, deep stretching yoga for flexibility and relaxation.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=yin+yoga+deep+stretch+relaxation",
    exercises: [
      { name: "Child's pose", durationSec: 300 },
      { name: "Dragon pose", durationSec: 300 },
      { name: "Butterfly pose", durationSec: 300 },
      { name: "Sphinx pose", durationSec: 300 },
      { name: "Savasana", durationSec: 300 },
    ],
  },
  {
    key: "strength-core",
    name: "Core Strength Builder",
    category: "Strength", level: "Beginner", durationMin: 20, caloriesEstimate: 150,
    description: "Focused core strengthening with dumbbells and bodyweight.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=core+strength+workout+dumbbells",
    exercises: [
      { name: "Dumbbell wood chops", durationSec: 60, rest: 30 },
      { name: "Pallof press", durationSec: 60, rest: 30 },
      { name: "Dead bugs", durationSec: 60, rest: 30 },
      { name: "Bird dogs", durationSec: 60, rest: 30 },
      { name: "Plank variations", durationSec: 60, rest: 30 },
      { name: "Cool-down", durationSec: 90 },
    ],
  },
  {
    key: "strength-cardio",
    name: "Strength & Cardio Combo",
    category: "Strength", level: "Advanced", durationMin: 45, caloriesEstimate: 350,
    description: "High-intensity strength training combined with cardio bursts.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=strength+cardio+combo+workout+advanced",
    exercises: [
      { name: "Dumbbell thrusters", durationSec: 45, rest: 15 },
      { name: "Burpees", durationSec: 45, rest: 15 },
      { name: "Kettlebell swings", durationSec: 45, rest: 15 },
      { name: "Mountain climbers", durationSec: 45, rest: 15 },
      { name: "Dumbbell snatches", durationSec: 45, rest: 15 },
      { name: "Jump squats", durationSec: 45, rest: 15 },
      { name: "Cool-down", durationSec: 90 },
    ],
  },
  {
    key: "calis-mobility",
    name: "Calisthenics Mobility",
    category: "Calisthenics", level: "Intermediate", durationMin: 28, caloriesEstimate: 180,
    description: "Bodyweight exercises focused on mobility and flexibility.",
    image: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=calisthenics+mobility+workout",
    exercises: [
      { name: "Arm circles", durationSec: 60, rest: 15 },
      { name: "Leg swings", durationSec: 60, rest: 15 },
      { name: "Inchworms", durationSec: 60, rest: 15 },
      { name: "Bodyweight squats", durationSec: 60, rest: 15 },
      { name: "Push-up to downward dog", durationSec: 60, rest: 15 },
      { name: "Lunges with twist", durationSec: 60, rest: 15 },
      { name: "Cool-down stretch", durationSec: 90 },
    ],
  },
  {
    key: "calis-endurance",
    name: "Calisthenics Endurance",
    category: "Calisthenics", level: "Intermediate", durationMin: 30, caloriesEstimate: 240,
    description: "High-rep bodyweight circuits for muscular endurance.",
    image: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=800&q=70",
    youtubeUrl: "https://www.youtube.com/results?search_query=calisthenics+endurance+circuit+workout",
    exercises: [
      { name: "Push-ups", durationSec: 60, rest: 20 },
      { name: "Squats", durationSec: 60, rest: 20 },
      { name: "Dips", durationSec: 60, rest: 20 },
      { name: "Lunges", durationSec: 60, rest: 20 },
      { name: "Pull-ups", durationSec: 60, rest: 20 },
      { name: "Plank hold", durationSec: 60, rest: 20 },
      { name: "Cool-down", durationSec: 90 },
    ],
  },
];

export type ExerciseLibraryItem = {
  name: string;
  category: "Pilates" | "HIIT" | "Yoga" | "Strength" | "Calisthenics";
  description: string;
  defaultDurationSec: number;
};

export const EXERCISE_LIBRARY: ExerciseLibraryItem[] = [
  // Pilates
  { name: "Hundred", category: "Pilates", description: "Core engagement with arm pumps", defaultDurationSec: 60 },
  { name: "Roll-up", category: "Pilates", description: "Spinal articulation and flexibility", defaultDurationSec: 60 },
  { name: "Single-leg stretch", category: "Pilates", description: "Core stability and coordination", defaultDurationSec: 60 },
  { name: "Double-leg stretch", category: "Pilates", description: "Deep core strengthening", defaultDurationSec: 60 },
  { name: "Spine stretch forward", category: "Pilates", description: "Hamstring and spine flexibility", defaultDurationSec: 60 },
  { name: "Saw", category: "Pilates", description: "Spinal rotation and flexibility", defaultDurationSec: 60 },
  { name: "Mermaid stretch", category: "Pilates", description: "Side body stretch and mobility", defaultDurationSec: 45 },
  { name: "Leg circles", category: "Pilates", description: "Hip mobility and core stability", defaultDurationSec: 60 },
  { name: "Teaser", category: "Pilates", description: "Advanced core strength", defaultDurationSec: 45 },
  { name: "Boomerang", category: "Pilates", description: "Full body coordination", defaultDurationSec: 45 },
  
  // HIIT
  { name: "Jumping jacks", category: "HIIT", description: "Full body cardio warm-up", defaultDurationSec: 40 },
  { name: "Squat jumps", category: "HIIT", description: "Explosive leg power", defaultDurationSec: 40 },
  { name: "Burpees", category: "HIIT", description: "Full body high-intensity move", defaultDurationSec: 40 },
  { name: "Mountain climbers", category: "HIIT", description: "Core and cardio combo", defaultDurationSec: 40 },
  { name: "High knees", category: "HIIT", description: "Cardio and hip flexor strength", defaultDurationSec: 40 },
  { name: "Speed skaters", category: "HIIT", description: "Lateral agility and power", defaultDurationSec: 45 },
  { name: "Tuck jumps", category: "HIIT", description: "Explosive vertical power", defaultDurationSec: 45 },
  { name: "Jump rope", category: "HIIT", description: "Cardio and coordination", defaultDurationSec: 45 },
  { name: "Box jumps", category: "HIIT", description: "Explosive lower body power", defaultDurationSec: 45 },
  { name: "Burpee box jumps", category: "HIIT", description: "Advanced full body power", defaultDurationSec: 45 },
  
  // Yoga
  { name: "Child's pose", category: "Yoga", description: "Restorative hip and back stretch", defaultDurationSec: 60 },
  { name: "Cat-cow", category: "Yoga", description: "Spinal mobility and warm-up", defaultDurationSec: 60 },
  { name: "Downward dog", category: "Yoga", description: "Full body stretch and inversion", defaultDurationSec: 60 },
  { name: "Sun salutation A", category: "Yoga", description: "Flowing warm-up sequence", defaultDurationSec: 120 },
  { name: "Warrior II", category: "Yoga", description: "Strength and balance pose", defaultDurationSec: 60 },
  { name: "Triangle pose", category: "Yoga", description: "Side body stretch and strength", defaultDurationSec: 60 },
  { name: "Seated twist", category: "Yoga", description: "Spinal rotation and digestion", defaultDurationSec: 60 },
  { name: "Savasana", category: "Yoga", description: "Final relaxation pose", defaultDurationSec: 180 },
  { name: "Vinyasa flow", category: "Yoga", description: "Dynamic flowing sequence", defaultDurationSec: 120 },
  { name: "Pigeon pose", category: "Yoga", description: "Deep hip opener", defaultDurationSec: 90 },
  
  // Strength
  { name: "Goblet squats", category: "Strength", description: "Lower body strength with weight", defaultDurationSec: 60 },
  { name: "Romanian deadlifts", category: "Strength", description: "Posterior chain strength", defaultDurationSec: 60 },
  { name: "Bench press", category: "Strength", description: "Chest and tricep strength", defaultDurationSec: 60 },
  { name: "Bent-over rows", category: "Strength", description: "Back and bicep strength", defaultDurationSec: 60 },
  { name: "Overhead press", category: "Strength", description: "Shoulder and core strength", defaultDurationSec: 60 },
  { name: "Walking lunges", category: "Strength", description: "Leg strength and balance", defaultDurationSec: 60 },
  { name: "Dumbbell flyes", category: "Strength", description: "Chest isolation exercise", defaultDurationSec: 60 },
  { name: "Bicep curls", category: "Strength", description: "Arm strength isolation", defaultDurationSec: 60 },
  { name: "Tricep extensions", category: "Strength", description: "Arm strength isolation", defaultDurationSec: 60 },
  { name: "Shoulder raises", category: "Strength", description: "Shoulder isolation exercise", defaultDurationSec: 60 },
  
  // Calisthenics
  { name: "Push-ups", category: "Calisthenics", description: "Upper body bodyweight strength", defaultDurationSec: 45 },
  { name: "Pull-ups", category: "Calisthenics", description: "Back and arm bodyweight strength", defaultDurationSec: 45 },
  { name: "Dips", category: "Calisthenics", description: "Chest and tricep bodyweight strength", defaultDurationSec: 45 },
  { name: "Squats", category: "Calisthenics", description: "Lower body bodyweight strength", defaultDurationSec: 45 },
  { name: "Lunges", category: "Calisthenics", description: "Single leg strength and balance", defaultDurationSec: 45 },
  { name: "Plank", category: "Calisthenics", description: "Core stability hold", defaultDurationSec: 45 },
  { name: "Glute bridges", category: "Calisthenics", description: "Glute and core strength", defaultDurationSec: 45 },
  { name: "Handstand hold", category: "Calisthenics", description: "Advanced shoulder strength", defaultDurationSec: 45 },
  { name: "L-sit", category: "Calisthenics", description: "Advanced core and arm strength", defaultDurationSec: 45 },
  { name: "Muscle-ups", category: "Calisthenics", description: "Advanced pulling power", defaultDurationSec: 45 },
];

export const SLEEP_SOUNDS = [
  { key: "rain", name: "Gentle Rain", emoji: "🌧️" },
  { key: "ocean", name: "Ocean Waves", emoji: "🌊" },
  { key: "forest", name: "Forest Night", emoji: "🌲" },
  { key: "wind", name: "Soft Wind", emoji: "🍃" },
  { key: "fire", name: "Fireplace", emoji: "🔥" },
  { key: "white", name: "White Noise", emoji: "📻" },
];
