"""Constants for Self-Trained AI System."""

# Data Types
DATA_TYPE_WORKOUT = "workout"
DATA_TYPE_MEAL = "meal"
DATA_TYPE_SLEEP = "sleep"
DATA_TYPE_MOOD = "mood"
DATA_TYPE_CYCLE = "cycle"

VALID_DATA_TYPES = [
    DATA_TYPE_WORKOUT,
    DATA_TYPE_MEAL,
    DATA_TYPE_SLEEP,
    DATA_TYPE_MOOD,
    DATA_TYPE_CYCLE,
]

# Feedback Types
FEEDBACK_TYPE_POSITIVE = "positive"
FEEDBACK_TYPE_NEGATIVE = "negative"
FEEDBACK_TYPE_NEUTRAL = "neutral"
FEEDBACK_TYPE_RATING = "rating"

VALID_FEEDBACK_TYPES = [
    FEEDBACK_TYPE_POSITIVE,
    FEEDBACK_TYPE_NEGATIVE,
    FEEDBACK_TYPE_NEUTRAL,
    FEEDBACK_TYPE_RATING,
]

# Model Status
MODEL_STATUS_TRAINING = "training"
MODEL_STATUS_TRAINED = "trained"
MODEL_STATUS_FAILED = "failed"
MODEL_STATUS_DEPRECATED = "deprecated"

VALID_MODEL_STATUSES = [
    MODEL_STATUS_TRAINING,
    MODEL_STATUS_TRAINED,
    MODEL_STATUS_FAILED,
    MODEL_STATUS_DEPRECATED,
]

# Recommendation Status
RECOMMENDATION_STATUS_PENDING = "pending"
RECOMMENDATION_STATUS_ACCEPTED = "accepted"
RECOMMENDATION_STATUS_REJECTED = "rejected"
RECOMMENDATION_STATUS_COMPLETED = "completed"

VALID_RECOMMENDATION_STATUSES = [
    RECOMMENDATION_STATUS_PENDING,
    RECOMMENDATION_STATUS_ACCEPTED,
    RECOMMENDATION_STATUS_REJECTED,
    RECOMMENDATION_STATUS_COMPLETED,
]

# Personalization Dimensions
DIMENSION_WORKOUT_FREQUENCY = "workout_frequency"
DIMENSION_WORKOUT_INTENSITY = "workout_intensity_preference"
DIMENSION_WORKOUT_TYPE = "workout_type_preference"
DIMENSION_MEAL_TIMING = "meal_timing_patterns"
DIMENSION_MEAL_TYPE = "meal_type_preferences"
DIMENSION_SLEEP_DURATION = "sleep_duration_patterns"
DIMENSION_SLEEP_QUALITY = "sleep_quality_patterns"
DIMENSION_MOOD = "mood_patterns"
DIMENSION_STRESS = "stress_level_patterns"
DIMENSION_GOAL_PROGRESS = "goal_progress_rate"
DIMENSION_FEEDBACK = "feedback_patterns"

PERSONALIZATION_DIMENSIONS = [
    DIMENSION_WORKOUT_FREQUENCY,
    DIMENSION_WORKOUT_INTENSITY,
    DIMENSION_WORKOUT_TYPE,
    DIMENSION_MEAL_TIMING,
    DIMENSION_MEAL_TYPE,
    DIMENSION_SLEEP_DURATION,
    DIMENSION_SLEEP_QUALITY,
    DIMENSION_MOOD,
    DIMENSION_STRESS,
    DIMENSION_GOAL_PROGRESS,
    DIMENSION_FEEDBACK,
]

# Workout Types
WORKOUT_TYPE_CARDIO = "cardio"
WORKOUT_TYPE_STRENGTH = "strength"
WORKOUT_TYPE_FLEXIBILITY = "flexibility"
WORKOUT_TYPE_SPORTS = "sports"
WORKOUT_TYPE_YOGA = "yoga"
WORKOUT_TYPE_PILATES = "pilates"
WORKOUT_TYPE_HIIT = "hiit"
WORKOUT_TYPE_WALKING = "walking"
WORKOUT_TYPE_RUNNING = "running"
WORKOUT_TYPE_CYCLING = "cycling"

VALID_WORKOUT_TYPES = [
    WORKOUT_TYPE_CARDIO,
    WORKOUT_TYPE_STRENGTH,
    WORKOUT_TYPE_FLEXIBILITY,
    WORKOUT_TYPE_SPORTS,
    WORKOUT_TYPE_YOGA,
    WORKOUT_TYPE_PILATES,
    WORKOUT_TYPE_HIIT,
    WORKOUT_TYPE_WALKING,
    WORKOUT_TYPE_RUNNING,
    WORKOUT_TYPE_CYCLING,
]

# Workout Intensity Levels
INTENSITY_LOW = "low"
INTENSITY_MODERATE = "moderate"
INTENSITY_HIGH = "high"
INTENSITY_VERY_HIGH = "very_high"

VALID_INTENSITY_LEVELS = [INTENSITY_LOW, INTENSITY_MODERATE, INTENSITY_HIGH, INTENSITY_VERY_HIGH]

# Meal Types
MEAL_TYPE_BREAKFAST = "breakfast"
MEAL_TYPE_LUNCH = "lunch"
MEAL_TYPE_DINNER = "dinner"
MEAL_TYPE_SNACK = "snack"
MEAL_TYPE_BEVERAGE = "beverage"

VALID_MEAL_TYPES = [
    MEAL_TYPE_BREAKFAST,
    MEAL_TYPE_LUNCH,
    MEAL_TYPE_DINNER,
    MEAL_TYPE_SNACK,
    MEAL_TYPE_BEVERAGE,
]

# Mood Levels
MOOD_VERY_SAD = "very_sad"
MOOD_SAD = "sad"
MOOD_NEUTRAL = "neutral"
MOOD_HAPPY = "happy"
MOOD_VERY_HAPPY = "very_happy"

VALID_MOOD_LEVELS = [MOOD_VERY_SAD, MOOD_SAD, MOOD_NEUTRAL, MOOD_HAPPY, MOOD_VERY_HAPPY]

# Sleep Quality Levels
SLEEP_QUALITY_POOR = "poor"
SLEEP_QUALITY_FAIR = "fair"
SLEEP_QUALITY_GOOD = "good"
SLEEP_QUALITY_EXCELLENT = "excellent"

VALID_SLEEP_QUALITY_LEVELS = [
    SLEEP_QUALITY_POOR,
    SLEEP_QUALITY_FAIR,
    SLEEP_QUALITY_GOOD,
    SLEEP_QUALITY_EXCELLENT,
]

# Cycle Phases
CYCLE_PHASE_MENSTRUATION = "menstruation"
CYCLE_PHASE_FOLLICULAR = "follicular"
CYCLE_PHASE_OVULATION = "ovulation"
CYCLE_PHASE_LUTEAL = "luteal"

VALID_CYCLE_PHASES = [
    CYCLE_PHASE_MENSTRUATION,
    CYCLE_PHASE_FOLLICULAR,
    CYCLE_PHASE_OVULATION,
    CYCLE_PHASE_LUTEAL,
]

# Error Messages
ERROR_INSUFFICIENT_DATA = "Insufficient training data for model training"
ERROR_MODEL_NOT_FOUND = "Model not found for user"
ERROR_INVALID_DATA_TYPE = "Invalid data type"
ERROR_INVALID_FEEDBACK_TYPE = "Invalid feedback type"
ERROR_MODEL_TRAINING_FAILED = "Model training failed"
ERROR_RECOMMENDATION_GENERATION_FAILED = "Recommendation generation failed"
ERROR_DATABASE_ERROR = "Database error"
ERROR_CACHE_ERROR = "Cache error"
ERROR_INVALID_REQUEST = "Invalid request"
ERROR_UNAUTHORIZED = "Unauthorized"
ERROR_NOT_FOUND = "Not found"
ERROR_INTERNAL_SERVER_ERROR = "Internal server error"

# Success Messages
SUCCESS_MODEL_TRAINED = "Model trained successfully"
SUCCESS_RECOMMENDATIONS_GENERATED = "Recommendations generated successfully"
SUCCESS_FEEDBACK_RECORDED = "Feedback recorded successfully"
SUCCESS_DATA_COLLECTED = "Data collected successfully"

# HTTP Status Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_CONFLICT = 409
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_SERVICE_UNAVAILABLE = 503

# Cache Keys
CACHE_KEY_MODEL = "model:{user_id}"
CACHE_KEY_RECOMMENDATIONS = "recommendations:{user_id}:{context_hash}"
CACHE_KEY_USER_PROFILE = "user_profile:{user_id}"
CACHE_KEY_FEATURES = "features:{user_id}"

# Time Constants (in seconds)
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86400
SECONDS_PER_WEEK = 604800
SECONDS_PER_MONTH = 2592000  # 30 days

# Confidence Thresholds
MIN_CONFIDENCE_THRESHOLD = 0.0
MAX_CONFIDENCE_THRESHOLD = 1.0
DEFAULT_CONFIDENCE_THRESHOLD = 0.6
HIGH_CONFIDENCE_THRESHOLD = 0.8
LOW_CONFIDENCE_THRESHOLD = 0.3

# Accuracy Thresholds
MIN_ACCURACY_THRESHOLD = 0.0
MAX_ACCURACY_THRESHOLD = 1.0
ACCEPTABLE_ACCURACY_THRESHOLD = 0.6
GOOD_ACCURACY_THRESHOLD = 0.8

# Personalization Score Range
MIN_PERSONALIZATION_SCORE = 0
MAX_PERSONALIZATION_SCORE = 100

# Feature Normalization
FEATURE_MIN_VALUE = 0.0
FEATURE_MAX_VALUE = 1.0

# Recommendation Ranking
MAX_RECOMMENDATIONS_PER_CATEGORY = 10
MIN_RECOMMENDATIONS_PER_CATEGORY = 1
DEFAULT_RECOMMENDATIONS_PER_CATEGORY = 5

# Model Versioning
MODEL_VERSION_FORMAT = "{timestamp}_{hash}"
MODEL_ARCHIVE_RETENTION_DAYS = 30

# Batch Processing
DEFAULT_BATCH_SIZE = 100
MAX_BATCH_SIZE = 1000

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Rate Limiting
DEFAULT_RATE_LIMIT = 100
DEFAULT_RATE_LIMIT_WINDOW = 3600  # 1 hour
