/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWorkoutsLogRouteImport } from './routes/_app.workouts-log'
import { Route as AppWorkoutsRouteImport } from './routes/_app.workouts'
import { Route as AppSleepRouteImport } from './routes/_app.sleep'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlansRouteImport } from './routes/_app.plans'
import { Route as AppMentalRouteImport } from './routes/_app.mental'
import { Route as AppHealthyLivingRouteImport } from './routes/_app.healthy-living'
import { Route as AppFocusRouteImport } from './routes/_app.focus'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCycleRouteImport } from './routes/_app.cycle'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutsLogRoute = AppWorkoutsLogRouteImport.update({
  id: '/workouts-log',
  path: '/workouts-log',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppSleepRoute = AppSleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppMentalRoute = AppMentalRouteImport.update({
  id: '/mental',
  path: '/mental',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthyLivingRoute = AppHealthyLivingRouteImport.update({
  id: '/healthy-living',
  path: '/healthy-living',
  getParentRoute: () => AppRoute,
} as any)
const AppFocusRoute = AppFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCycleRoute = AppCycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/cycle': typeof AppCycleRoute
  '/dashboard': typeof AppDashboardRoute
  '/focus': typeof AppFocusRoute
  '/healthy-living': typeof AppHealthyLivingRoute
  '/mental': typeof AppMentalRoute
  '/plans': typeof AppPlansRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/search': typeof AppSearchRoute
  '/sleep': typeof AppSleepRoute
  '/workouts': typeof AppWorkoutsRoute
  '/workouts-log': typeof AppWorkoutsLogRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/cycle': typeof AppCycleRoute
  '/dashboard': typeof AppDashboardRoute
  '/focus': typeof AppFocusRoute
  '/healthy-living': typeof AppHealthyLivingRoute
  '/mental': typeof AppMentalRoute
  '/plans': typeof AppPlansRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/search': typeof AppSearchRoute
  '/sleep': typeof AppSleepRoute
  '/workouts': typeof AppWorkoutsRoute
  '/workouts-log': typeof AppWorkoutsLogRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/cycle': typeof AppCycleRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/focus': typeof AppFocusRoute
  '/_app/healthy-living': typeof AppHealthyLivingRoute
  '/_app/mental': typeof AppMentalRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/sleep': typeof AppSleepRoute
  '/_app/workouts': typeof AppWorkoutsRoute
  '/_app/workouts-log': typeof AppWorkoutsLogRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/cycle'
    | '/dashboard'
    | '/focus'
    | '/healthy-living'
    | '/mental'
    | '/plans'
    | '/profile'
    | '/recommendations'
    | '/search'
    | '/sleep'
    | '/workouts'
    | '/workouts-log'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/cycle'
    | '/dashboard'
    | '/focus'
    | '/healthy-living'
    | '/mental'
    | '/plans'
    | '/profile'
    | '/recommendations'
    | '/search'
    | '/sleep'
    | '/workouts'
    | '/workouts-log'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/cycle'
    | '/_app/dashboard'
    | '/_app/focus'
    | '/_app/healthy-living'
    | '/_app/mental'
    | '/_app/plans'
    | '/_app/profile'
    | '/_app/recommendations'
    | '/_app/search'
    | '/_app/sleep'
    | '/_app/workouts'
    | '/_app/workouts-log'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workouts-log': {
      id: '/_app/workouts-log'
      path: '/workouts-log'
      fullPath: '/workouts-log'
      preLoaderRoute: typeof AppWorkoutsLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sleep': {
      id: '/_app/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof AppSleepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mental': {
      id: '/_app/mental'
      path: '/mental'
      fullPath: '/mental'
      preLoaderRoute: typeof AppMentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/healthy-living': {
      id: '/_app/healthy-living'
      path: '/healthy-living'
      fullPath: '/healthy-living'
      preLoaderRoute: typeof AppHealthyLivingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/focus': {
      id: '/_app/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AppFocusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cycle': {
      id: '/_app/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof AppCycleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCycleRoute: typeof AppCycleRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFocusRoute: typeof AppFocusRoute
  AppHealthyLivingRoute: typeof AppHealthyLivingRoute
  AppMentalRoute: typeof AppMentalRoute
  AppPlansRoute: typeof AppPlansRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSleepRoute: typeof AppSleepRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
  AppWorkoutsLogRoute: typeof AppWorkoutsLogRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCycleRoute: AppCycleRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFocusRoute: AppFocusRoute,
  AppHealthyLivingRoute: AppHealthyLivingRoute,
  AppMentalRoute: AppMentalRoute,
  AppPlansRoute: AppPlansRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSleepRoute: AppSleepRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
  AppWorkoutsLogRoute: AppWorkoutsLogRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
